import Foundation
import XCTest
@testable import StrandAnalytics

/// `ResilienceEngine` is validated the way AGENTS.md asks of any signal derived from raw data: it must
/// RECOVER several injected recovery times, not match one. Each synthetic series is an OU process with a
/// known τ (7, 14, 28 or 56 days) plus the structure real step counts carry: a weekday pattern, memoryless
/// day noise and 20 % missing days. The 90 % interval must cover the truth in at least 85 % of seeds, and
/// the estimate must track the input. The negative controls (white noise, a strong trend, a weekly
/// pattern) must not read as memory.
///
/// The 480-run study behind that is pinned in `oracles/resilience.json`, generated by the `-O` twin in
/// `Tools/oracle-twins/resilience_twin.swift`: each estimate inverts a bootstrap of about 2,000 simulated
/// series, which a debug-built test cannot afford 480 times. The live re-runs below recompute a spread of
/// the pinned cases, so the file is proven to come from the engine as it is now.
final class ResilienceOracleTests: XCTestCase {

    typealias E = ResilienceEngine

    /// Must match `synthetic` in `Tools/oracle-twins/resilience_twin.swift` exactly.
    static func synthetic(tau: Double?, seed: UInt64, trend: Double = 0, sigma: Double = 0.4) -> [E.DayValue] {
        var rng = E.SplitMix64(seed: seed &* 7919 &+ 17)
        let week = [0.25, 0.1, 0.05, 0.0, 0.05, -0.2, -0.3]
        let phi = tau.map { exp(-1 / $0) } ?? 0
        let a = tau == nil ? 0 : 0.7
        var y = rng.nextGaussian()
        var out: [E.DayValue] = []
        for d in 0..<180 {
            if d > 0 { y = phi * y + (1 - phi * phi).squareRoot() * rng.nextGaussian() }
            let noise = rng.nextGaussian()
            let v = 8.8 + sigma * (a.squareRoot() * y + (1 - a).squareRoot() * noise) + week[d % 7]
                + trend * Double(d)
            if rng.nextUniform() < 0.2 { continue }
            out.append(E.DayValue(dayIndex: d, value: exp(v)))
        }
        return out
    }

    private func loadOracle() throws -> [String: Any] {
        let relative = "Packages/StrandAnalytics/Tests/StrandAnalyticsTests/oracles/resilience.json"
        var directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = directory.appendingPathComponent(relative)
            if FileManager.default.fileExists(atPath: candidate.path) {
                let object = try JSONSerialization.jsonObject(with: Data(contentsOf: candidate))
                let root = try XCTUnwrap(object as? [String: Any])
                XCTAssertEqual(root["schemaVersion"] as? Int, 1)
                XCTAssertFalse(try XCTUnwrap(root["note"] as? String).isEmpty)
                // The pinned study ran at the engine's current bootstrap size.
                XCTAssertEqual(root["defaultReplicates"] as? Int, E.defaultReplicates)
                XCTAssertEqual(root["calibrationGridPoints"] as? Int, E.calibrationGridPoints)
                return root
            }
            directory = directory.deletingLastPathComponent()
        }
        XCTFail("committed oracle \(relative) not found above \(#filePath)")
        throw CocoaError(.fileNoSuchFile)
    }

    private func number(_ d: [String: Any], _ key: String) throws -> Double {
        try XCTUnwrap(d[key] as? NSNumber, key).doubleValue
    }

    private func assertMatches(_ e: E.Estimate, _ row: [String: Any], _ label: String,
                               file: StaticString = #filePath, line: UInt = #line) throws {
        for (key, got) in [("tau", e.tau), ("tauLow", e.tauLow), ("tauHigh", e.tauHigh),
                           ("tauFit", e.tauFit), ("amplitude", e.amplitude), ("sigma", e.sigma)] {
            XCTAssertEqual(got, try number(row, key), accuracy: 1e-9, "\(label) \(key)", file: file, line: line)
        }
    }

    // MARK: - The pinned study

    func testTheIntervalCoversSeveralInjectedRecoveryTimes() throws {
        let rows = try XCTUnwrap(try loadOracle()["recovery"] as? [[String: Any]])
        XCTAssertEqual(rows.count, 400)
        var medians: [Double] = []
        for tau in [7.0, 14, 28, 56] {
            let group = try rows.filter { try number($0, "trueTau") == tau }
            XCTAssertEqual(group.count, 100)
            var covered = 0
            for r in group {
                let (est, low, high) = (try number(r, "tau"), try number(r, "tauLow"), try number(r, "tauHigh"))
                XCTAssertLessThanOrEqual(low, est)
                XCTAssertLessThanOrEqual(est, high)
                if low <= tau && tau <= high { covered += 1 }
            }
            // A nominal 90 % interval; the pinned study measures 86, 88, 89 and 93.
            XCTAssertGreaterThanOrEqual(covered, 85, "τ \(tau): covered in \(covered) of 100 seeds")
            let estimates = try group.map { try number($0, "tau") }.sorted()
            medians.append(estimates[50])
        }
        // The estimate tracks the input: a longer injected τ reads longer at every step, and the median
        // lands within a factor 1.5 of the truth.
        XCTAssertEqual(medians, medians.sorted())
        for (median, tau) in zip(medians, [7.0, 14, 28, 56]) {
            XCTAssertLessThan(max(median / tau, tau / median), 1.5, "τ \(tau) median \(median)")
        }
    }

    func testTheControlsDoNotReadAsMemory() throws {
        let rows = try XCTUnwrap(try loadOracle()["controls"] as? [[String: Any]])
        for kind in ["white", "trend", "weekly"] {
            let group = rows.filter { $0["kind"] as? String == kind }
            XCTAssertEqual(group.count, 20)
            var atFloor = 0
            for r in group {
                // Never a confident memory: the interval always reaches down to the floor, and the
                // estimate never comes near a week.
                XCTAssertEqual(try number(r, "tauLow"), E.tauFloor, "\(kind)")
                XCTAssertLessThan(try number(r, "tau"), 5, "\(kind)")
                if try number(r, "tau") == E.tauFloor { atFloor += 1 }
                // White noise leaves the interval open (nothing rules out a long τ either).
                if kind == "white" { XCTAssertGreaterThan(try number(r, "tauHigh"), 60) }
                if try number(r, "amplitude") < E.minAmplitude { XCTAssertEqual(try number(r, "tau"), E.tauFloor) }
            }
            XCTAssertGreaterThanOrEqual(atFloor, 18, "\(kind): \(atFloor) of 20 at the floor")
        }
    }

    // MARK: - Live re-runs

    /// The first seed of every group, recomputed now and compared with what the twin printed.
    func testASpreadOfThePinnedCasesReproducesLive() throws {
        let root = try loadOracle()
        let recovery = try XCTUnwrap(root["recovery"] as? [[String: Any]])
        for tau in [7.0, 14, 28, 56] {
            let row = try XCTUnwrap(try recovery.first { try number($0, "trueTau") == tau })
            let seed = try XCTUnwrap(row["seed"] as? NSNumber).uint64Value
            let live = try XCTUnwrap(E.analyze(series: Self.synthetic(tau: tau, seed: seed), signal: .steps)?.estimate)
            try assertMatches(live, row, "τ \(tau) seed \(seed)")
        }
        let controls = try XCTUnwrap(root["controls"] as? [[String: Any]])
        for kind in ["white", "trend", "weekly"] {
            let row = try XCTUnwrap(controls.first { $0["kind"] as? String == kind })
            let seed = try XCTUnwrap(row["seed"] as? NSNumber).uint64Value
            let series = Self.synthetic(tau: nil, seed: seed, trend: try number(row, "trend"),
                                        sigma: try number(row, "noiseSD"))
            let live = try XCTUnwrap(E.analyze(series: series, signal: .steps)?.estimate)
            try assertMatches(live, row, "\(kind) seed \(seed)")
        }
    }

    /// One run pinned in full (estimate, autocorrelation and knocks), from the series stored in the file.
    func testTheDetailedRunReproducesLive() throws {
        let row = try XCTUnwrap(try loadOracle()["detailed"] as? [String: Any])
        let points = try XCTUnwrap(row["series"] as? [[NSNumber]])
        let series = points.map { E.DayValue(dayIndex: $0[0].intValue, value: $0[1].doubleValue) }
        let result = try XCTUnwrap(E.analyze(series: series, signal: .steps))
        XCTAssertEqual(result.observedDays, row["observedDays"] as? Int)
        XCTAssertEqual(result.endDay, row["endDay"] as? Int)
        let live = try XCTUnwrap(result.estimate)
        try assertMatches(live, row, "detailed")
        let acf = try XCTUnwrap(row["acf"] as? [Any])
        XCTAssertEqual(acf.count, E.maxLag)
        for (k, value) in acf.enumerated() {
            let want = (value as? NSNumber)?.doubleValue
            XCTAssertEqual(live.acf[k] == nil, want == nil, "lag \(k + 1)")
            if let got = live.acf[k], let want { XCTAssertEqual(got, want, accuracy: 1e-12, "lag \(k + 1)") }
        }
        XCTAssertEqual(live.acfPairs, row["acfPairs"] as? [Int])

        let knocks = try XCTUnwrap(row["knocks"] as? [[String: Any]])
        XCTAssertFalse(knocks.isEmpty)
        let liveKnocks = E.knocks(series: series, signal: .steps)
        XCTAssertEqual(liveKnocks.count, knocks.count)
        for (k, want) in zip(liveKnocks, knocks) {
            XCTAssertEqual(k.startDay, want["startDay"] as? Int)
            XCTAssertEqual(k.peakDay, want["peakDay"] as? Int)
            XCTAssertEqual(k.peakDeviation, try number(want, "peakDeviation"), accuracy: 1e-12)
            XCTAssertEqual(k.daysToBaseline, want["daysToBaseline"] as? Int)
            XCTAssertEqual(k.path.map(\.dayIndex), want["pathDays"] as? [Int])
            let values = try XCTUnwrap(want["pathValues"] as? [NSNumber]).map(\.doubleValue)
            for (got, v) in zip(k.path.map(\.value), values) { XCTAssertEqual(got, v, accuracy: 1e-12) }
            XCTAssertEqual(k.halfLifeDays == nil, want["halfLifeDays"] == nil)
            if let h = k.halfLifeDays { XCTAssertEqual(h, try number(want, "halfLifeDays"), accuracy: 1e-9) }
            if let p = k.returnAmplitude { XCTAssertEqual(p, try number(want, "returnAmplitude"), accuracy: 1e-9) }
        }
    }
}
