// resilience_twin.swift — regenerates
// Packages/StrandAnalytics/Tests/StrandAnalyticsTests/oracles/resilience.json.
//
//   SRC=Packages/StrandAnalytics/Sources/StrandAnalytics
//   swiftc -O -parse-as-library $SRC/ResilienceEngine.swift Tools/oracle-twins/resilience_twin.swift \
//       -o /tmp/resilience_twin && /tmp/resilience_twin \
//       > Packages/StrandAnalytics/Tests/StrandAnalyticsTests/oracles/resilience.json
//
// Compiled standalone with ResilienceEngine.swift, it runs the engine over synthetic series with KNOWN
// recovery times and prints every case's inputs and outputs. The study is too heavy for a debug-built test
// (each estimate inverts a 2,000-replicate bootstrap), so ResilienceOracleTests reads the coverage from
// this file and re-runs a spread of its cases live, which proves the file came from the current engine.
import Foundation

typealias E = ResilienceEngine

/// Must match `ResilienceOracleTests.synthetic` exactly: the live re-runs fail otherwise.
func synthetic(tau: Double?, seed: UInt64, trend: Double = 0, sigma: Double = 0.4) -> [E.DayValue] {
    var rng = E.SplitMix64(seed: seed &* 7919 &+ 17)
    let week = [0.25, 0.1, 0.05, 0.0, 0.05, -0.2, -0.3]
    let phi = tau.map { exp(-1 / $0) } ?? 0
    let a = tau == nil ? 0 : 0.7
    var y = rng.nextGaussian()
    var out: [E.DayValue] = []
    for d in 0..<180 {
        if d > 0 { y = phi * y + (1 - phi * phi).squareRoot() * rng.nextGaussian() }
        let noise = rng.nextGaussian()
        let v = 8.8 + sigma * (a.squareRoot() * y + (1 - a).squareRoot() * noise) + week[d % 7]
            + trend * Double(d)
        if rng.nextUniform() < 0.2 { continue }
        out.append(E.DayValue(dayIndex: d, value: exp(v)))
    }
    return out
}

func row(_ e: E.Estimate, _ extra: [String: Any]) -> [String: Any] {
    var d = extra
    d["tau"] = e.tau
    d["tauLow"] = e.tauLow
    d["tauHigh"] = e.tauHigh
    d["tauFit"] = e.tauFit
    d["amplitude"] = e.amplitude
    d["sigma"] = e.sigma
    return d
}

@main
struct ResilienceTwin {
    static func main() throws {
        let seedsPerTau = 100
        var recovery: [[String: Any]] = []
        for tau in [7.0, 14, 28, 56] {
            for s in 0..<seedsPerTau {
                let seed = UInt64(s) + UInt64(tau) * 1000
                let e = E.analyze(series: synthetic(tau: tau, seed: seed), signal: .steps)!.estimate!
                recovery.append(row(e, ["trueTau": tau, "seed": seed]))
            }
        }
        var controls: [[String: Any]] = []
        for (kind, base, trend, sigma) in [("white", 99, 0.0, 0.4), ("trend", 500, 0.01, 0.4),
                                            ("weekly", 700, 0.0, 0.2)] {
            for s in 0..<20 {
                let seed = UInt64(s + base)
                let e = E.analyze(series: synthetic(tau: nil, seed: seed, trend: trend, sigma: sigma),
                                  signal: .steps)!.estimate!
                controls.append(row(e, ["kind": kind, "seed": seed, "trend": trend, "noiseSD": sigma]))
            }
        }
        // One run pinned in full, series included, so the test does not depend on the generator for it.
        let series = synthetic(tau: 14, seed: 3)
        let full = E.analyze(series: series, signal: .steps)!
        let e = full.estimate!
        var detailed = row(e, ["observedDays": full.observedDays, "endDay": full.endDay])
        detailed["series"] = series.map { [$0.dayIndex, $0.value] as [Any] }
        detailed["acf"] = e.acf.map { $0 as Any? ?? NSNull() }
        detailed["acfPairs"] = e.acfPairs
        detailed["knocks"] = E.knocks(series: series, signal: .steps).map { k -> [String: Any] in
            var d: [String: Any] = ["startDay": k.startDay, "peakDay": k.peakDay,
                                    "peakDeviation": k.peakDeviation, "pathDays": k.path.map(\.dayIndex),
                                    "pathValues": k.path.map(\.value)]
            if let v = k.daysToBaseline { d["daysToBaseline"] = v }
            if let v = k.halfLifeDays { d["halfLifeDays"] = v }
            if let v = k.returnAmplitude { d["returnAmplitude"] = v }
            return d
        }

        let root: [String: Any] = [
            "schemaVersion": 1,
            "note": "ResilienceEngine over synthetic OU series with known tau (weekday pattern, nugget 0.3, "
                + "20% missing days), plus white-noise, trend and weekly-only controls. Generated by "
                + "Tools/oracle-twins/resilience_twin.swift; do not edit by hand.",
            "defaultReplicates": E.defaultReplicates,
            "calibrationGridPoints": E.calibrationGridPoints,
            "recovery": recovery,
            "controls": controls,
            "detailed": detailed,
        ]
        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        FileHandle.standardOutput.write(data)
        FileHandle.standardOutput.write("\n".data(using: .utf8)!)
    }
}
